[package]
name = "rtiow"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
image = { version = "0.25.2", default-features = false, features = ["png", "rayon"] }
rand = "0.8.5"

[profile.release]
codegen-units = 1
# lto = "fat"