[package]
name = "rtiow"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["common"]

[workspace.dependencies]
rand = { version = "0.9.2", default-features = false, features = ["small_rng"] }

[dependencies]
color-eyre = "0.6.3"
image = { version = "0.25.2", default-features = false, features = ["png", "rayon"] }
rand.workspace = true
rayon = "1.10.0"
common = { path = "common" }

[profile.release]
codegen-units = 1
panic = "abort"
# lto = "fat"
